# Generated by Django 5.1.1 on 2024-10-08 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jogo",
            name="time_mandante_escudo",
        ),
        migrations.RemoveField(
            model_name="jogo",
            name="time_visitante_escudo",
        ),
    ]
