# Generated by Django 5.1.1 on 2024-12-17 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogador',
            name='posicao',
            field=models.IntegerField(choices=[(1, 'Goleiro'), (2, 'Fixo'), (3, 'Ala'), (4, 'Pivo')]),
        ),
    ]
