# Generated by Django 5.0.6 on 2024-08-14 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_campeonato"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rodada",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("numero_rodada", models.IntegerField()),
                ("data_inicio", models.DateField()),
                ("data_termino", models.DateField()),
            ],
        ),
    ]
