# Generated by Django 5.0.6 on 2024-08-14 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_campeonato"),
    ]

    operations = [
        migrations.CreateModel(
            name="Time",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=100)),
                ("gols_pro", models.IntegerField(blank=True)),
                ("gols_contra", models.IntegerField(blank=True)),
                ("vitoria", models.IntegerField(blank=True)),
                ("derrota", models.IntegerField(blank=True)),
                ("pontos", models.IntegerField(blank=True)),
            ],
        ),
    ]
