# Generated by Django 5.1.1 on 2024-10-19 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_jogo_time_mandante_escudo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timejogador",
            name="jogador",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="time", to="core.jogador"
            ),
        ),
    ]
