# Generated by Django 5.1.1 on 2024-10-19 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_timejogador_jogador"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timejogador",
            name="jogador",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="times", to="core.jogador"
            ),
        ),
    ]
