# Generated by Django 5.0.6 on 2024-08-14 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="time",
            name="derrota",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="time",
            name="gols_contra",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="time",
            name="gols_pro",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="time",
            name="pontos",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="time",
            name="vitoria",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
