# Generated by Django 5.0.6 on 2024-08-20 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rodada'),
        ('core', '0004_alter_time_derrota_alter_time_gols_contra_and_more'),
    ]

    operations = [
    ]
