# Generated by Django 5.0.6 on 2024-08-20 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_merge_20240820_1400"),
    ]

    operations = [
        migrations.CreateModel(
            name="Jogador",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=100)),
                ("idade", models.IntegerField(blank=True, max_length=2, null=True)),
                ("email", models.EmailField(max_length=150)),
                ("posicao", models.CharField(max_length=150, null=True)),
                ("numero", models.IntegerField(blank=True, max_length=2, null=True)),
            ],
        ),
    ]
