# Generated by Django 5.0.6 on 2024-08-20 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_merge_20240820_1400"),
    ]

    operations = [
        migrations.CreateModel(
            name="Jogo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("data", models.DateField()),
                ("horario", models.TimeField()),
                ("endereco", models.CharField(max_length=150)),
                ("gols", models.JSONField(blank=True, null=True)),
                ("cartoes", models.JSONField(blank=True, null=True)),
                (
                    "rodada",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="jogos", to="core.rodada"
                    ),
                ),
                (
                    "time_mandante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="jogos_mandante", to="core.time"
                    ),
                ),
                (
                    "time_visitante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="jogos_visitante", to="core.time"
                    ),
                ),
            ],
        ),
    ]
