# Generated by Django 5.1.1 on 2024-10-30 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_time_empate"),
    ]

    operations = [
        migrations.AddField(
            model_name="jogo",
            name="vencedor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="vitorias",
                to="core.time",
            ),
        ),
    ]
