# Generated by Django 5.0.6 on 2024-08-20 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_jogador'),
        ('core', '0006_jogo'),
    ]

    operations = [
    ]
