# Generated by Django 5.0.6 on 2024-08-20 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_merge_0006_jogador_0006_jogo"),
    ]

    operations = [
        migrations.AddField(
            model_name="jogador",
            name="time",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="jogador",
                to="core.time",
            ),
        ),
        migrations.AlterField(
            model_name="jogador",
            name="idade",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="jogador",
            name="numero",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="jogador",
            name="posicao",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
