# Generated by Django 5.1.1 on 2024-11-18 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_jogo_vencedor"),
    ]

    operations = [
        migrations.AddField(
            model_name="campeonato",
            name="mata_mata",
            field=models.BooleanField(default=False),
        ),
    ]
