# Generated by Django 5.1.1 on 2024-11-18 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_campeonato_mata_mata"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rodada",
            name="data_inicio",
        ),
        migrations.RemoveField(
            model_name="rodada",
            name="data_termino",
        ),
    ]
