# Generated by Django 5.0.6 on 2024-08-20 19:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alter_jogador_numero"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jogador",
            name="numero",
            field=models.PositiveIntegerField(
                blank=True,
                default=0,
                null=True,
                validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(1)],
            ),
        ),
    ]
