# Generated by Django 5.0.6 on 2024-08-20 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_alter_jogador_numero"),
    ]

    operations = [
        migrations.AddField(
            model_name="rodada",
            name="campeonato",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rodada",
                to="core.campeonato",
            ),
        ),
    ]
