# Generated by Django 5.1.1 on 2024-11-19 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_rodada_data_inicio_remove_rodada_data_termino'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogo',
            name='tipo_jogo',
            field=models.CharField(choices=[('GP', 'Grupo'), ('SF', 'Semi'), ('FN', 'Final')], default='GP', max_length=3),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='posicao',
            field=models.CharField(choices=[(1, 'Goleiro'), (2, 'Fixo'), (3, 'Ala'), (4, 'Pivo')], max_length=10),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='data',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='endereco',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='horario',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='rodada',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='jogos', to='core.rodada'),
        ),
    ]
