# Generated by Django 5.0.6 on 2024-08-20 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_rodada_campeonato"),
    ]

    operations = [
        migrations.AddField(
            model_name="time",
            name="campeonato",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="time",
                to="core.campeonato",
            ),
        ),
    ]
