# Generated by Django 5.1.1 on 2024-11-27 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_alter_jogo_data_alter_jogo_endereco_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="passage_id",
        ),
    ]
