# Generated by Django 5.0.6 on 2024-08-21 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_time_campeonato"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jogador",
            name="time",
        ),
    ]
