# Generated by Django 5.0.6 on 2024-08-21 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_remove_jogador_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimeJogador",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("data_inicio", models.DateField()),
                ("data_termino", models.DateField()),
                (
                    "jogador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="jogador", to="core.jogador"
                    ),
                ),
                (
                    "time",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="time", to="core.time"),
                ),
            ],
        ),
    ]
