# Generated by Django 5.1.1 on 2024-12-03 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_remove_user_passage_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timejogador",
            name="jogador",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="times", to="core.jogador"
            ),
        ),
        migrations.AlterField(
            model_name="timejogador",
            name="time",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="jogadores", to="core.time"
            ),
        ),
    ]
