# Generated by Django 5.0.6 on 2024-08-21 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_timejogador"),
    ]

    operations = [
        migrations.AddField(
            model_name="jogador",
            name="time_jogador",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="time_jogador",
                to="core.timejogador",
            ),
        ),
    ]
