# Generated by Django 5.0.6 on 2024-08-21 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_jogador_time_jogador"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jogador",
            name="time_jogador",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="time_jogador",
                to="core.timejogador",
            ),
        ),
    ]
