# Generated by Django 5.1.1 on 2024-12-12 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_timejogador_data_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogo',
            name='time_mandante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jogos_mandante', to='core.time'),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='time_visitante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jogos_visitante', to='core.time'),
        ),
    ]
