# Generated by Django 5.1.1 on 2024-12-13 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_jogo_time_mandante_alter_jogo_time_visitante'),
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='escudo',
            field=models.ForeignKey(blank=True, default='https://i.ibb.co/VDwW5Rv/28-289657-espn-soccer-team-logo-default.png', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='uploader.image'),
        ),
    ]
