# Generated by Django 5.1.1 on 2024-12-17 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_jogo_tipo_jogo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campeonato',
            name='mata_mata',
        ),
    ]
